# accounts
user_name: "{{app_name}}"
group_name: "{{app_name}}"
# paths
deploy_root: "/opt/{{app_name}}"
src_root: "{{deploy_root}}/src"
static_root: "{{src_root}}/static"
# nginx
http_port: 80
# misc
webapp_archive_location: /tmp/src.tar.gz
# required packages
required_apt_packages:
    - build-essential
    - rsync
    - python3
    - python3-pip
    - python3-dev
    - software-properties-common
    - nginx
    - curl
    - sudo
nginx_user: www-data
nginx_group: www-data
pip_executable: /usr/bin/pip3
nginx_sites_dir: /etc/nginx/sites-enabled
