- name: setup group
  action: group name={{group_name}} state=present
- name: setup user
  action: user name={{user_name}} state=present group={{group_name}}
- name: set up apt packages
  action: apt pkg={{item}} state=latest update_cache=yes
  with_items: "{{required_apt_packages}}"
- name: set up virtualenv
  pip: name=virtualenv state=latest executable={{pip_executable}}
- name: ensure directories
  action: file state=directory path={{item}} owner={{user_name}} group={{group_name}}
  with_items:
    - "{{deploy_root}}"
    - "{{deploy_root}}/conf.d"
- name: ensure no nginx default conf
  action: file path=/etc/nginx/sites-enabled/default state=absent
- name: nginx running
  action: service name=nginx state=started enabled=yes
- include: configuration.yml
- name: copy source
  copy: src=../src_pkg.tar.gz dest={{webapp_archive_location}}
  register: sources
- include: install_sources.yml
  when: sources.changed or configuration.changed
- name: ensure /var/run/{{app_name}} directory on boot
  template: src=../templates/tmpfiles.d.conf.j2 dest=/etc/tmpfiles.d/{{app_name}}.conf
- file: path=/var/run/{{app_name}} state=directory mode=0770 owner={{app_name}} group={{nginx_group}}
- name: install systemd service
  action: template src=../templates/gunicorn.service.j2 dest=/lib/systemd/system/{{app_name}}-wsgi.service
  when: sources.changed or configuration.changed
  register: systemd_change
- name: reload systemd daemon
  action: shell systemctl daemon-reload
  when: systemd_change.changed
- name: enable the services
  action: service name={{app_name}}-wsgi enabled=true state=started
- name: restart the service if code changes
  shell: systemctl restart {{app_name}}-wsgi
  when: systemd_change.changed or sources.changed or configuration.changed
- name: try to get local page
  shell: curl http://localhost/
